# CI for Chain on Linux Environment
name: Linux-Environment

on:
  push:
    branches:
      - main
    tags:
      - v1.*
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: self-hosted
    name: Check Formatting Job
    steps:
    - uses: actions/checkout@v2

    - name: Install rustfmt so that we can call "cargo fmt"
      run: rustup component add rustfmt

    - name: Check that the code is properly formatted
      run: /root/.cargo/bin/cargo fmt --all -- --check

  tests:
    runs-on: self-hosted
    name: Run Tests Job
    if: ${{ always() }}
    needs: format
    steps:
    - uses: actions/checkout@v2

    - name: Check that all the tests are passing 
      run: /root/.cargo/bin/cargo test --all-targets --all-features --workspace

  build:
    runs-on: self-hosted
    name: Build Binary Job
    if: ${{ always() }}
    needs: tests
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Ternoa client
      run: /root/.cargo/bin/cargo build --release

    - name: Configure AWS credentials from Test account
      uses: s3-actions/s3cmd@v0
      with:
        provider: "aws"
        access_key: ${{ secrets.SW_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.SW_SECRET_ACCESS_KEY }}
        region: fr-par
        
    - name: Copy Binary to Scaleway Bucket /chain/${GITHUB_REF##*/}/latest
      run: |
        s3cmd sync ./target/release/ternoa s3://ternoa/chain/${GITHUB_REF##*/}/linux/ternoa --host https://s3.fr-par.scw.cloud --host-bucket https://s3.fr-par.scw.cloud --acl-public

    - name: Copy Binary to Scaleway Bucket  ${{ github.sha }}.zip
      run: |
        s3cmd sync ./target/release/ternoa s3://ternoa/chain/${GITHUB_REF##*/}/linux/${{ github.sha }} --host https://s3.fr-par.scw.cloud --host-bucket https://s3.fr-par.scw.cloud --acl-public
        
    - name: Notify Ops
      uses: craftech-io/slack-action@v1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
