name: Run Benchmarks Manual

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime'
        required: true
        type: choice
        options:
        - alphanet
        - mainnet
        - chaosnet

env:
  CARGO_TERM_COLOR: always
  Runtime: ${{ github.event.inputs.runtime }}


jobs:
  run-benchmarks:
    runs-on: min-spec
    name: Run Benchmarks
    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust toolchain
      run: rustup show

    - name: Build the Ternoa client
      run: cargo build --release --features runtime-benchmarks

    - name: Run benchmarks
      run: ./scripts/benchmarks/"$Runtime"/run_benchmarks.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
        path: weights

    