name: Run Cargo Format and Run Tests

on:
  push:
    branches:
      - main
    tags:
      - v1.*
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check Formatting Job
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        run: rustup show

      - name: Check that the code is properly formatted
        run: cargo fmt --all -- --check

  tests:
    runs-on: ubuntu-latest
    name: Run Tests Job
    if: ${{ always() }}
    needs: format
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        run: rustup show

      - name: Check that all the tests are passing 
        run: cargo test --all-targets --all-features --workspace